version: '3.8'
services:
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      PASSWORD: 'ohm13112523'
      MYSQL_DATABASE: database_nectec_nlp
      MYSQL_PASSWORD: ohm13112523
      
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
  web:
    build: .
    command: 
        - /bin/bash
        - -c
        - |
          sleep 10
          python3 manage.py migrate
          python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project_nectec
    ports:
      - "8000:8000"
    depends_on:
         - db

# version: '3.8'
# services:
#   db:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: "root"
#       PASSWORD: 'ohm13112523'
#       MYSQL_DATABASE: database_nectec_nlp
#       MYSQL_PASSWORD: ohm13112523
#       TZ: 'Asia/Tokyo'
#     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#   web:
#     build: .
#     command: python3 manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/project_nectec
#     ports:
#       - "8000:8000"
#     depends_on:
#          - db